name: CI/CD

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: 'poetry'

      - name: Install linting tools
        run: poetry install --only dev

      - name: Run Black
        run: black --check sherlock tests

      - name: Run iSort
        run: isort --check sherlock tests

      - name: Run flake8
        run: flake8 sherlock tests

      - name: Run pycodestyle
        run: pycodestyle sherlock tests

  test:
    name: Test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    env:
      REDIS_HOST: 127.0.0.1
      ETCD_HOST: 127.0.0.1
      MEMCACHED_HOST: 127.0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          cache: 'poetry'

      - name: Install `libmemcached-dev`
        run: sudo apt-get install -y libmemcached-dev

      - name: Install sherlock
        run: poetry install --all-extras

      - name: Run tests
        run: poetry run tox

      - uses: codecov/codecov-action@v3
