name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release to PyPi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Build
        run: poetry build

      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: |
          poetry config pypi-token.pypi "$POETRY_PYPI_TOKEN_PYPI"
          poetry publish
